---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: monocle
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - bash
            - -c
            - "export $(cat /etc/monocle-secrets/.secrets) && monocle api"
          env:
            - name: MONOCLE_ELASTIC_URL
              value: http://elastic:9200
          image: quay.io/change-metrics/monocle:1.11.1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 6
            timeoutSeconds: 60
          name: api
          ports:
            - containerPort: 8080
              name: http-rest-api
          resources: {}
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
            - mountPath: /etc/monocle-secrets
              name: monocle-secret-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config
        - name: monocle-secret-volume
          secret:
            secretName: monocle-secrets
