---
apiVersion: v1
# created manually using the command:
# oc create configmap --from-file=config.yaml monocle-config --dry-run=client -oyaml
kind: ConfigMap
metadata:
  name: monocle-config
  labels:
    app.kubernetes.io/part-of: monocle
data:
  config.yaml: |+
    workspaces:
      - name: demo
        crawlers: []

