apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: api-legacy
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: monocle
  name: api-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-legacy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api-legacy
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - uwsgi
            - --http
            - :9876
            - --socket
            - :9877
            - --manage-script-name
            - --mount
            - /app=monocle.webapp:app
          env:
            - name: CLIENT_ID
            - name: CLIENT_SECRET
            - name: CONFIG
              value: /etc/monocle/config.yaml
            - name: ELASTIC_CONN
              value: elastic:9200
            - name: PUBLIC_URL
              value: http://localhost:8080
          image: quay.io/change-metrics/monocle_backend:latest
          livenessProbe:
            exec:
              command:
                - python -c "
                  import requests,sys
                  r=requests.get('http://localhost:9876/api/0/health')
                  print(r.text)
                  sys.exit(1) if r.status_code!=200 else sys.exit(0)
                  "
            failureThreshold: 6
            timeoutSeconds: 60
          name: api-legacy
          ports:
            - containerPort: 9876
              name: http-rest-api
          resources: {}
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config
status: {}
