---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: monocle
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - monocle
            - api
          env:
            - name: CONFIG
              value: /etc/monocle/config.yaml
            - name: ELASTIC_CONN
              value: elastic:9200
            - name: CHANGE_ME
              value: change_me # done as the value in ./monocle-config.yaml requires an envvar by the name CHANGE_ME to exist
          image: quay.io/change-metrics/monocle_api:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 6
            timeoutSeconds: 60
          name: api
          ports:
            - containerPort: 8080
              name: http-rest-api
          resources: {}
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config # ./monocle-config.yaml
status: {}
