apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: elastic
    app.kubernetes.io/part-of: monocle
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elastic
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: elastic
        app.kubernetes.io/component: elastic
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          livenessProbe:
            exec:
              command:
                - curl --silent --fail localhost:9200/_cluster/health || exit 1
            failureThreshold: 6
            timeoutSeconds: 60
          name: elastic
          ports:
            - containerPort: 9200
              name: rest
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data-volume
      restartPolicy: Always
      volumes:
        - name: elastic-data-volume
          persistentVolumeClaim:
            claimName: elastic-data
status: {}
