apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: monocle
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://localhost:8080
            - name: REACT_APP_TITLE
          image: quay.io/change-metrics/monocle_web:latest
          name: web
          ports:
            - containerPort: 8080
              name: web
          resources: {}
# commented as the non-mounted uses the ../web/conf/nginx.conf
#         volumeMounts:
#           - mountPath: /etc/nginx/conf.d
#             name: nginx-config-volume
      restartPolicy: Always
#     volumes:
#       - name: nginx-config-volume
#         emptyDir: {}
status: {}
