jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
        with:
          submodules: 'true'
      - uses: "cachix/install-nix-action@v15"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "cachix/cachix-action@v10"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: change-metrics
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: "elastic/elastic-github-actions/elasticsearch@master"
        with:
          stack-version: '7.8.0'
      - name: Display indexes
        run: curl -s -I -X GET http://localhost:9200/_cat/indices
      - name: Build the env
        run: nix-build --no-out-link --attr monocle-light.env
      - name: Run Test
        run: "cd haskell; nix-shell --pure --attr ci-shell ../nix/default.nix --command 'env MONOCLE_ELASTIC_URL=http://localhost:9200 monocle-ci-run'"
name: Nix
on:
  pull_request: {}
