jobs:
  publish-master-container:
    if: "github.repository_owner == 'change-metrics'"
    name: publish-builder-container
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
        with:
          submodules: 'true'
      - name: Stop provided Docker
        run: sudo systemctl stop docker containerd
      - name: Remove provided Docker
        run: sudo apt-get remove --autoremove -y moby-engine moby-cli moby-buildx moby-containerd moby-runc
      - name: Install patched seccomp Docker repository
        run: sudo add-apt-repository -y ppa:pascallj/docker.io-clone3
      - name: Install patched seccomp Docker
        run: sudo apt-get install -y docker.io
      - name: Build Builder image
        run: docker build -f Dockerfile-builder -t quay.io/change-metrics/builder .
      - name: Publish image to quay.io
        run: "docker login -u \"${{ secrets.QUAYIO_USERNAME }}\" -p \"${{ secrets.QUAYIO_PASSWORD }}\" quay.io && docker push quay.io/change-metrics/builder:latest"
name: Publish Builder Container
on:
  workflow_dispatch: {}
