name: PR validation
on: pull_request

jobs:
  tox:
    if: github.repository_owner == 'change-metrics'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.8.0

      - name: Display indexes
        run: curl -s -I -X GET http://localhost:9200/_cat/indices

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -e py3

      # - name: Validate usefulness of tests
      #   uses: quality-of-tests/has-useful-tests-action@master
      #   with:
      #     run-tests: tox -epy3
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Build docker images
        run: |
          ln -s docker-compose.yml.dev docker-compose.yml
          cat > .secrets << EOF
          CRAWLERS_API_KEY=secret
          GITHUB_TOKEN=123
          EOF
          docker-compose build

      - name: Set write permission for others for data directory
        run: |
          chmod o+w data

      - name: Create a config.yaml file
        run: |
          cat > etc/config.yaml << EOL
          ---
          workspaces:
            - name: monocle
              crawlers:
                - name: github-tekton
                  update_since: "2020-01-01"
                  provider:
                    github_organization: tekton
          EOL

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 45

      - name: Display docker-compose information
        run: |
          docker-compose ps
          docker-compose logs

      - name: Check services are running
        run: test -z "$(sudo docker-compose ps -a | grep Exit)"

      - name: Check api service
        run: curl -s http://localhost:8080/api/2/get_workspaces

      - name: Check web service
        run: curl -s http://localhost:8080/

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm packages
        run: |
          sudo apt-get install git
          cd web ; npm install

      - name: Run npm test
        run: |
          cd web ; npm run test

      - name: Run npm format
        run: |
          cd web && npm run format
